# Generated by Django 5.0.3 on 2024-04-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littleapp', '0003_remove_recipe_likes_recipe_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeLike',
        ),
    ]
